# Generated by Django 2.1.1 on 2018-10-31 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_eimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eimage',
            field=models.ImageField(default='C:/Users/Dell/Documents/newdjango/crud4/employee/static/default.png', upload_to='media'),
        ),
    ]
