# Generated by Django 2.1.1 on 2018-10-31 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20181031_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='eimage',
            field=models.ImageField(default='/media/default.png', upload_to='media'),
        ),
    ]
